name: Trigger CodeRabbit Review

on:
  pull_request:
    types: [opened]

jobs:
  trigger-review:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment as bot
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "@coderabbitai review"
